import Head from 'next/head'
import Image from 'next/image'
import DogCard from '../components/DogCard'
import useSWR, { useSWRConfig } from "swr"
import { fetcher } from '../API/fetcher'
import { useMemo, useState } from 'react'

export default function Home() {
  const { data } = useSWR('https://dog.ceo/api/breeds/list/all', fetcher)
  const breeds = useMemo(() => {
    if (data) {
      const breedList = Object.keys(data)
      return breedList
    } else {
      []
    }
  }, [data])

  const [selected, setSelected] = useState(null)

  const handleChange = (e) => {
    setSelected(e.target.value)
  }

  return (
    <div>
      <Head>
        <title>Dog API test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://dog.ceo/img/dog-api-logo.svg" />
      </Head>
      <main className='grid w-screen mt-20 space-y-4 m-auto items-center justify-around'>
        <select className='h-auto capitalize border p-4 rounded-md' onChange={(e) => handleChange(e)}>
          <option value="none" selected disabled hidden>Select an Option</option>
          {breeds?.map((breed, index) => (
            <option key={`${index}-${breed}`} value={breed}>{breed}</option>
          ))}
        </select>
        <DogCard selected={selected} />
      </main>
    </div>
  )
}
